name: Build and deploy Docker image to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read     
  packages: write     
  id-token: write     

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/ismailalhazzaa/mocklyai-whisper:latest

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A0FEFBF82FF649C7B3585518B0CBFB8F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7A4AD84B7B1483089D29D8F26309472 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C9DC8BE1E267420BA06431A3441947B1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mocklyai-whisper'
          images: 'ghcr.io/${{ github.repository_owner }}/mocklyai-whisper:latest'
